name: Build and publish wheels

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check if secret is present
        shell: bash
        run: |
          if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
            echo "❌ PYPI_API_TOKEN is NOT set"
            exit 1
          else
            echo "✅ PYPI_API_TOKEN is present"
          fi

      - uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --no-sdist
          manylinux: auto
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
